### ISSUE TITLE
Why not shader graph on water shader?

### ISSUE THREAD

**Issue by RobertoPelonara** [Unity-Technologies/BoatAttack#116]
I think one of the best way of learning something like shader graph is by analyzing how shaders are composed. 

I followed a tutorial on YT of making shader graph water and I'm pretty happy with the result, but that tutorial is pointing me here with no water shader graph.

**Comment by Verasl** [comment]
So the two main reasons it has yet to be ported are:
- There is no way to do a for loop in shadergraph, this is needed for custom lighting with additional lights(nicely) and also the softer shadows on the water
- No way to do vertex only calculations and pass that as custom data to the fragment(pixel) shader, right now since the water mesh is fairly dense for the wave displacement, a lot of shader calcuations can be done vertex only which saves a ton of processing

There are a few smaller issues stopping me from converting it over fully, at the end of the day, a water shader is quite complex and current shadergraph doesnt give you enough fine grained control over the little details in shaders, custom shader states, extra/custom passes, tesselation. There is work being done to address these so I'm looking forward to being able to convert it over one day.

Saying that there are a few shader graphs in this project to look at, cliffs, vegetation, boat colouring, clouds(wip) are a few, and I will be adding more as I finish off this project.
