### ISSUE TITLE
can not work

### ISSUE THREAD

**Issue by gongxiaobo** [Unity-Technologies/BoatAttack#22]
I download the master project from here ,using unity 2019 ,but I import it,it not works,no textures noly white box

**Comment by Image3D** [comment]
Same Problem here...

**Comment by Sea4U** [comment]
I meet the same problem using the last Unity（Unity 2019.1.0a12 (64-bit)）

**Comment by Verasl** [comment]
This repo uses GitLFS, this is to store all the textures and meshes since they are quite large. When downloading the zip these files are not included and can only be acquired via cloning down the repo with a version control software such as Sourcetree to Fork, then you will pull down all the needed files with GitLFS.

In the coming months I plan to upload some builds along side this repo so people can download and run the demo without needing to pull the entire project. I might also upload some full zipped versions that can easily be used.
