### ISSUE TITLE
manifest.json on master

### ISSUE THREAD

**Issue by adrenak** [Unity-Technologies/BoatAttack#25]
Hi, I'm trying to run the project on the master branch on Unity 2018.3. 

manifest.json (https://github.com/Verasl/BoatAttack/blob/master/Packages/manifest.json) has some local paths in the file and is failing

**Comment by Verasl** [comment]
Hey!

Yes the manifest on master is meant to be pointing to a local cloned version of SRP, this is because master is likely to only work with latest SRP master so a package entry is unusable. If you are wanting to use this with a package available in the package manager, make sure to pull one of the 'Package/x.x.x' branches, these have normal package entries in the manifest.

Cheers,
Andre

**Comment by Verasl** [comment]
btw, for 18.3 I would suggest 'Packages/4.x.x' as these are the versions compatible with 18.3
