### ISSUE TITLE
ERROR All Asset and Package

### ISSUE THREAD

**Issue by ImanCol** [Unity-Technologies/BoatAttack#38]
I am receiving many errors from your project. I am using it in the last beta of 2019.1.0bx and it was given to me to download the extacted version 2019.1.0b6 and it keeps presenting those errors.

![image](https://user-images.githubusercontent.com/26169049/56254073-e24a9900-6084-11e9-9b2a-b16592afe035.png)

![image](https://user-images.githubusercontent.com/26169049/56254099-073f0c00-6085-11e9-9287-c287c1b64f45.png)

![image](https://user-images.githubusercontent.com/26169049/56254116-0f974700-6085-11e9-926e-03a2e031e1aa.png)

![image](https://user-images.githubusercontent.com/26169049/56254125-18881880-6085-11e9-9c3e-9c0e82a5832e.png)

![image](https://user-images.githubusercontent.com/26169049/56254135-250c7100-6085-11e9-9078-00a2e5199596.png)

**Comment by PJ373** [comment]
Check the size of the files like with the audio files.  If you are seeing they are all 1 kb, you probably got the zipped file.  "Make sure you clone the repo as downloading the zip will not contain the LFS files(all textures/meshes etc)"

**Comment by PlopEHan** [comment]
You have to clone with Git Large File Storage (LFS).
Example: git lfs clone https://....

**Comment by ImanCol** [comment]
Thanks. Yes, you should have cloned the repository. Well, now everything seems to be fine, except for small mistakes.
![image](https://user-images.githubusercontent.com/26169049/56329340-9a8d4580-6148-11e9-9b1b-60006a3c3984.png)

**Comment by Verasl** [comment]
Yes, I have made it more clear in the readme that you will need GitLFS, also in soon I plan to make downloadable Zips so that you do not need to use Git and clone but rather just download the project.

The other errors you see have been fixed in the `release/2019.1` branch and will be fixed in following branches once I create them(hopefully today). They are harmless, mainly due to meshes having `import animation` by default even though there is not need for animation.

Glad you got it working in the end, and thanks to those who commented with suggestions :)
