### ISSUE TITLE
Way to change the foam texture(edges)?

### ISSUE THREAD

**Issue by Leeszaa** [Unity-Technologies/BoatAttack#46]
I kinda feel a bit stupid, but I couldnt finde a way to change the foam texture. Is there any way that I am overseeing?

**Comment by Verasl** [comment]
Not easily atm I'm afraid, you can tweak the amount of foam on the Water component, there are a few ways to do it. Otherwise to replace the foam currently it's easiest to just replace the current file. I'm planning on working on making the system easier to use and customise but with my other tasks it is hard to find time to spend on demo projects.
