### ISSUE TITLE
Human player not working?

### ISSUE THREAD

**Issue by Shadowing1983** [Unity-Technologies/BoatAttack#54]
I clicked on the red boat and checked Human but controls don't control the boat?
Is there something else I need to do?

**Comment by dan-asa** [comment]
Had the same problem. Fixed it by changing "Horizontal" and "Accellerate" axis Type to "Key or Mouse Button" in Input Manager.

**Comment by Shadowing1983** [comment]
Oh thanks i'll try it out again. Pretty sure this project is abandon now though. It was just a test show off project for Unity 2019.
so sad. I heard the code is all clean and organized though so thats great.

**Comment by Verasl** [comment]
Hey, the project is far from abandoned, it's just very hard to find time to spend on it with all that's going on with Universal Render Pipeline. I'm glad you found the solution, I'll be updating the `release/2019.3` branch today with a heap of updates since Unite Cph.

Also don't know where you heard the code was organised 😆 some is but there is also a lot of mess in here still to clean up 😞
