### ISSUE TITLE
Shouldn't this be 60, not 30?

### ISSUE THREAD

**Issue by prodigga** [Unity-Technologies/BoatAttack#57]
https://github.com/Verasl/BoatAttack/blob/5ee2c7561dad4087fa427ca96b687f8ffeed51f8/Assets/Scripts/GameSystem/AppSettings.cs#L81

Also, some comments/description would be much appreciated! I'm having trouble figuring out what the calculations are doing. From what I can understand, if it detects the frame rate is dropping bellow some number, it performs dynamic scaling to reduce rendering time. But the actual code with all the keeps and clamps and bias and offset floats is a bit hard to understand. 😔

Very nice repository overall though, generally very clean code and lots of ideas I'll be borrowing. Thanks :)

**Comment by Verasl** [comment]
Yes, yes it should be, thanks 😄 

As for the code itself, pretty much is give a positive or negative rate to which to scale the render texture. This is then clamped between the minimum scaling down, so say you don't want it less than 50% the resolution and no bigger than 100%. This scale is then either mixed evenly between the width and height or biased to affect one more than the other, say you are ok with loosing resolution across the X but not the Y, the bias controls this.

This stuff is pretty untouched since I first made it, and it needs some work and also better UI for tweaking it in the inspector. We are wanting to add this to Universal RP as a feature at some point but will have to wait a while.

I'm glad you're finding useful stuff in this project, that's what it's designed for.

**Comment by Verasl** [comment]
Fixed on `master` and `release/2019.3`
